<?php
require_once __DIR__ . '/vendor/autoload.php'; // Composer autoload
include '../connection.php'; // Database connection

use TCPDF;

// Extend TCPDF to create custom Header and Footer
class MYPDF extends TCPDF {
    // Page header
    public function Header() {
        $this->SetFont('dejavusans', 'B', 12);
        $this->Cell(0, 10, 'BARANGAY MAUJO - AID EVENTS REPORT', 0, 1, 'C');
        $this->SetFont('dejavusans', '', 10);
        $this->Cell(0, 8, 'Malitbog, Southern Leyte', 0, 1, 'C');
        $this->Ln(2);
    }

    // Page footer
    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('dejavusans', 'I', 9);
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().' of '.$this->getAliasNbPages(), 0, 0, 'C');
    }
}

// Fetch aid events
$stmt = $connection->query("SELECT * FROM aid_events ORDER BY date_started DESC");
$events = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Create PDF
$pdf = new MYPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('e-Barangay System');
$pdf->SetTitle('Aid Events Report');
$pdf->SetMargins(15, 35, 15); // Top margin increased for header
$pdf->SetAutoPageBreak(true, 25); // Bottom margin for footer
$pdf->AddPage();
$pdf->SetFont('dejavusans', '', 10);

// Table Header
$pdf->SetFillColor(230,230,230);
$pdf->Cell(10, 8, 'No.', 1, 0, 'C', 1);
$pdf->Cell(50, 8, 'Title', 1, 0, 'C', 1);
$pdf->Cell(30, 8, 'Type', 1, 0, 'C', 1);
$pdf->Cell(30, 8, 'Amount', 1, 0, 'C', 1);
$pdf->Cell(30, 8, 'Start Date', 1, 0, 'C', 1);
$pdf->Cell(30, 8, 'End Date', 1, 1, 'C', 1);

// Table Rows
$total = 0;
foreach ($events as $i => $event) {
    $pdf->Cell(10, 8, $i + 1, 1);
    $pdf->Cell(50, 8, $event['title'], 1);
    $pdf->Cell(30, 8, $event['type'], 1);
    $pdf->Cell(30, 8, '₱' . number_format($event['total_amount'], 2), 1);
    $pdf->Cell(30, 8, $event['date_started'], 1);
    $pdf->Cell(30, 8, $event['date_ended'], 1, 1);
    $total += $event['total_amount'];
}

// Totals
$pdf->Ln(5);
$pdf->Write(0, "Total Events: " . count($events), '', 0, 'L');
$pdf->Ln();
$pdf->Write(0, "Total Aid Amount: ₱" . number_format($total, 2), '', 0, 'L');

// Footer note (above TCPDF footer)
$pdf->Ln(10);
$pdf->SetFont('dejavusans', '', 9);
$pdf->Write(0, "Note: Auto-generated by e-Barangay System", '', 0, 'L');

// Output the PDF
$pdf->Output('Aid_Events_Report.pdf', 'I');
?>
