<?php
require_once __DIR__ . '/vendor/autoload.php';
include '../connection.php';

use TCPDF;

class MYPDF extends TCPDF {
    public function Header() {
        $logoPath = __DIR__ . '/../components/img/stock_image/brgy_logo.jpeg';
        if (file_exists($logoPath)) {
            // Logo on the left, adjusted size (e.g., 28x28 mm)
            $this->Image($logoPath, 15, 10, 28, 28, 'JPG');
        }
        // Set X to right after logo for header text block
        $this->SetXY(40, 12);
        $this->SetFont('dejavusans', 'B', 14);
        $this->Cell(155, 7, 'Republic of the Philippines', 0, 2, 'C', false);
        $this->SetFont('dejavusans', '', 11);
        $this->Cell(155, 6, 'Province of Southern Leyte', 0, 2, 'C', false);
        $this->Cell(155, 6, 'Municipality of Malitbog', 0, 2, 'C', false);
        $this->Cell(155, 6, 'Barangay Maujo', 0, 2, 'C', false);
        $this->SetFont('dejavusans', 'I', 9);
        $this->Cell(155, 5, 'Address: Maujo, Malitbog, Southern Leyte', 0, 2, 'C', false);
        $this->Ln(2);
        $this->SetDrawColor(50, 50, 50);
        $this->Line(15, $this->GetY(), 195, $this->GetY());
        $this->Ln(5);
    }

    public function Footer() {
        $this->SetY(-18);
        $this->SetFont('dejavusans', 'I', 9);
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().' of '.$this->getAliasNbPages(), 0, 0, 'C');
    }
}

$stmt = $connection->query("SELECT * FROM file_request WHERE transaction_type = 'Barangay Clearance' ORDER BY date_submitted DESC");
$events = $stmt->fetchAll(PDO::FETCH_ASSOC);

$pdf = new MYPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('e-Barangay System');
$pdf->SetTitle('Barangay Clearance Report');
$pdf->SetMargins(15, 40, 15);
$pdf->SetAutoPageBreak(true, 25);
$pdf->AddPage();

// Title Section
$pdf->Ln(10); // Add space above the title
$pdf->SetFont('dejavusans', 'B', 15);
$pdf->Cell(0, 12, 'Barangay Clearance Report', 0, 1, 'C');
$pdf->SetFont('dejavusans', '', 10);
$pdf->Cell(0, 8, 'Date Generated: ' . date('F j, Y'), 0, 1, 'R');
$pdf->Ln(2);

// Table Header
$pdf->SetFont('dejavusans', 'B', 10);
$pdf->SetFillColor(220,220,220);
// Adjusted column widths for better fit
$pdf->Cell(12, 8, 'No.', 1, 0, 'C', 1);
$pdf->Cell(40, 8, 'Name', 1, 0, 'C', 1);
$pdf->Cell(54, 8, 'Email', 1, 0, 'C', 1);
$pdf->Cell(20, 8, 'Amount', 1, 0, 'C', 1);
$pdf->Cell(34, 8, 'Date Submitted', 1, 0, 'C', 1);
$pdf->Cell(30, 8, 'Status', 1, 1, 'C', 1);

// Table Rows
$pdf->SetFont('dejavusans', '', 10);
$total = 0;
foreach ($events as $i => $event) {
    $pdf->Cell(12, 8, $i + 1, 1, 0, 'C');
    $pdf->Cell(40, 8, $event['name'], 1);
    $pdf->Cell(54, 8, $event['email'], 1);
    $pdf->Cell(20, 8, '₱' . number_format($event['amount'], 2), 1, 0, 'R');
    $pdf->Cell(34, 8, date('M j, Y', strtotime($event['date_submitted'])), 1, 0, 'C');
    $pdf->Cell(30, 8, $event['transaction_status'], 1, 1, 'C');
    $total += $event['amount'];
}


// Totals
$pdf->Ln(6);
$pdf->SetFont('dejavusans', 'B', 10);
$pdf->Cell(0, 8, "Total Barangay Clearance Requests: " . count($events), 0, 1, 'L');
$pdf->Cell(0, 8, "Total Amount Collected for Barangay Clearance Requests: ₱" . number_format($total, 2), 0, 1, 'L');

// Footer note
$pdf->Ln(10);
$pdf->SetFont('dejavusans', '', 9);
$pdf->Cell(0, 8, "Note: This report is auto-generated by the e-Barangay System.", 0, 1, 'L');

// Signature line
$pdf->Ln(15);
$pdf->SetFont('dejavusans', '', 10);
$pdf->Cell(0, 8, '______________________________________', 0, 1, 'R');
$pdf->Cell(0, 6, 'Barangay Captain / Authorized Official', 0, 1, 'R');

// Output the PDF
$pdf->Output('barangay_clearance_report.pdf', 'I');
?>
